---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador-pro
rules:
- apiGroups: ["stable.datawire.io"]
  resources:
  - policies
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador-pro
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador-pro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-pro
subjects:
- kind: ServiceAccount
  name: ambassador-pro
  namespace: datawire
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-pro
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: ambassador-pro
      allowed_headers:
       - "Authorization"
       - "Client-Id"
       - "Client-Secret"
spec:
  selector:
    name: ambassador-pro
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador-pro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ambassador-pro
    spec:
      serviceAccountName: ambassador-pro
      containers:
      - name: ambassador-pro
        image: quay.io/datawire/ambassador-pro:0.1
        ports:
        - containerPort: 8080
        env:
          - name: AUTH0_DOMAIN
            value: thelis.auth0.com
          - name: AUTH0_AUDIENCE
            value: friends
